# Generated by Django 4.2.5 on 2023-09-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogiverseApp', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
