# Generated by Django 4.2.5 on 2023-09-17 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YogiverseApp', '0004_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='YogiverseApp.mediafile'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user1', 'user2')},
        ),
    ]
