# Generated by Django 4.2.5 on 2023-09-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogiverseApp', '0005_statusupdate_media_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusupdate',
            name='media_file',
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='media_file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
