# Generated by Django 4.2.5 on 2023-09-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YogiverseApp', '0006_remove_statusupdate_media_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='file_path',
            new_name='media_file',
        ),
    ]
